server.port=0
spring.main.allow-bean-definition-overriding=true
spring.banner.location=classpath:banner-dev.txt

# ===============================
# Datasource H2 en memoria
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.devtools.restart.enabled=false
# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# No mostrar SQL en consola durante tests
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# Logging: solo errores para tests
# ===============================
logging.level.root=false
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.springframework.test.context=WARN
logging.level.org.springframework.boot.test.context=WARN